name: Android CI

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'


jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Fetch MAPS_API_KEY
      env:
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      run: echo maps_api_key=\"MAPS_API_KEY\" > ./local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Unit tests
      run: bash ./gradlew test --stacktrace
      
    - name: Upload html test report
      uses: actions/upload-artifact@v2
      with:
        name: index.html
        path: app/build/reports/tests/testDebugUnitTest/index.html

    - name: Upload test report directory
      uses: actions/upload-artifact@v2
      with:
        name: testDebugStuff
        path: app/build/reports/tests/testDebugUnitTest/

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CLIMATE_REPORTER_ID }}